working_directory: /mnt/c/Users/dfayad/Desktop/articles//eqasim-france/cache
run:
- synthesis.output
config:
  processes: 4
  hts: entd
  latent_classes.enabled: false
  target_population: null
  target_households: null
  baseline_run_id: baseline_occitanie_59510
  baseline_run_path: # expects something like: /mnt/c/eqasim-france/output/baselines/baseline_occitanie_59510
  sampling_rate: 0.01
  random_seed: 1234

  # Paths to the input data and where the output should be stored
  data_path: # expects something like: /mnt/c/eqasim-france/data
  output_path: # expects something like: /mnt/c/eqasim-france/output
  output_prefix: occitanie_
  output_formats:
  - csv
  - gpkg

  # Only interesting if you run the simulation
  java_memory: 14G
  mode_choice: false
  export_trips: false

  # Occitanie settings
  regions: []
  departments: [] # ["09", "82", "81", "11", "31", "32", "12", "30", "34", "46", "48", "65", "66"]


  gtfs_path: gtfs_occitanie
  ban_path: ban_occitanie
  bdtopo_path: bdtopo_occitanie
  bikesharing_path: bikesharing_occitanie
  gbfs_path: gbfs
  carsharing_path: carsharing_occitanie/station_information_carsharing_citiz_occitanie.json
  carpooling_path: carpooling_occitanie/infrastructures-de-covoiturage-en-occitanie-v2.csv

  taxi_data_paths:
  - taxi_pmr_occitanie/taxis_toulouse.json
  - taxi_pmr_occitanie/pmr_taxis_delivery_Montpellier.json

  pmr_data_paths:
  - taxi_pmr_occitanie/pmr_Toulouse.json
  - taxi_pmr_occitanie/pmr_taxis_delivery_Montpellier.json

  parking_data_paths: parking_occitanie

  pnr_data_paths: p+r

  income_assignation_method: bhepop2

  timetables_path: # expects something like: /mnt/c/eqasim-france/data/gtfs_occitanie/timetables/20260717_163230
  timetables_weekday: # expects something like: monday/tuesday/wednesday/thursday/friday/saturday/sunday

  taxi_fleet_path: # expects something like: /mnt/c/eqasim-france/data/taxi_occitanie/fleet/20260717_163230