const BACKEND_BASE = (import.meta.env.VITE_BACKEND_URL || 'http://localhost:8000').replace(/\/$/, '')
const RESOURCE_BASE = `${BACKEND_BASE}/resources`
/** Must match backend DEFAULT_BASELINE_RUN_ID / config_occitanie.yml baseline_run_id */
export const BASELINE_RUN_ID = 'baseline_occitanie_59510'

export const DEFAULT_MAP_VIEW = {
  center: [43.8, 2.2],
  zoom: 8,
}

export const RESOURCE_LAYERS = [
  {
    id: 'generatedPopulation',
    label: 'Generated population (latest run)',
    url: null,
    format: 'geojson',
    color: '#111827',
    popupFields: ['household_id', 'commune_id', 'departement_id'],
    defaultVisible: false,
  },
  {
    id: 'generatedActivities',
    label: 'Generated activities (latest run)',
    url: null,
    format: 'geojson',
    color: '#0ea5e9',
    popupFields: ['person_id', 'purpose', 'start_time', 'end_time', 'commune_id'],
    defaultVisible: false,
  },
  {
    id: 'bikesharing',
    label: 'Bikesharing stations',
    url: `${RESOURCE_BASE}/baselines/${BASELINE_RUN_ID}/${BASELINE_RUN_ID}_bikesharing_stations.csv`,
    skipCsvCache: true,
    outputSuffix: 'bikesharing_stations.csv',
    latField: 'lat',
    lonField: 'lon',
    color: '#1f77b4',
    popupFields: ['city_station_id', 'city_id', 'name', 'operator', 'station_id', 'available_bikes', 'capacity'],
    defaultVisible: false,
  },
  {
    id: 'gtfsStops',
    label: 'GTFS stops',
    url: `${RESOURCE_BASE}/baselines/${BASELINE_RUN_ID}/${BASELINE_RUN_ID}_gtfs_stops.csv`,
    skipCsvCache: true,
    outputSuffix: 'gtfs_stops.csv',
    latField: 'stop_lat',
    lonField: 'stop_lon',
    color: '#555555',
    popupFields: ['operator', 'feed_id', 'stop_name', 'stop_id'],
    defaultVisible: false,
  },
  {
    id: 'carsharing',
    label: 'Carsharing stations',
    url: `${RESOURCE_BASE}/occitanie_carsharing_stations.csv`,
    outputSuffix: 'carsharing_stations.csv',
    latField: 'lat',
    lonField: 'lon',
    color: '#ff7f0e',
    popupFields: ['name', 'station_id', 'address'],
    defaultVisible: false,
  },
  {
    id: 'carpooling',
    label: 'Carpooling stops',
    url: `${RESOURCE_BASE}/occitanie_carpooling_stops.csv`,
    outputSuffix: 'carpooling_stops.csv',
    latField: 'lat',
    lonField: 'lon',
    color: '#2ca02c',
    popupFields: ['nom_lieu', 'com_lieu', 'id_local'],
    defaultVisible: false,
  },
  {
    id: 'taxiStands',
    label: 'Taxi stands',
    url: `${RESOURCE_BASE}/occitanie_taxi_stands.csv`,
    outputSuffix: 'taxi_stands.csv',
    latField: 'lat',
    lonField: 'lon',
    color: '#d62728',
    popupFields: ['name', 'commune', 'nb_places', 'source_file'],
    defaultVisible: false,
  },
  {
    id: 'pmrStands',
    label: 'PMR stands',
    url: `${RESOURCE_BASE}/occitanie_pmr_stands.csv`,
    outputSuffix: 'pmr_stands.csv',
    latField: 'lat',
    lonField: 'lon',
    color: '#9467bd',
    popupFields: ['name', 'commune', 'nb_places', 'pmr_type', 'source_file'],
    defaultVisible: false,
  },
  {
    id: 'publicParking',
    label: 'Public parking',
    url: `${RESOURCE_BASE}/occitanie_public_parking.csv`,
    outputSuffix: 'public_parking.csv',
    latField: 'lat',
    lonField: 'lon',
    color: '#8c564b',
    popupFields: ['name', 'city', 'address', 'total_spaces', 'free_spaces', 'source_file'],
    defaultVisible: false,
  },
  {
    id: 'parkAndRide',
    label: 'Park and ride',
    url: `${RESOURCE_BASE}/occitanie_park_and_ride.csv`,
    outputSuffix: 'park_and_ride.csv',
    latField: 'lat',
    lonField: 'lon',
    color: '#0f766e',
    popupFields: ['name', 'city', 'address', 'park_and_ride_spaces', 'total_spaces', 'source_file'],
    defaultVisible: false,
  },
]
